# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Kaiwa — one spec, both platforms.

Run from the repo root:  pyinstaller packaging/kaiwa.spec
Produces dist/Kaiwa.app on macOS and dist/Kaiwa/ (onedir) on Windows.
The .dmg / .exe installers are wrapped around those by the CI workflow.
"""
import os
import sys

from PyInstaller.utils.hooks import collect_all, collect_submodules

IS_MAC = sys.platform == "darwin"
IS_WIN = os.name == "nt"

# Paths are resolved against the repo root (this spec lives in packaging/).
# SPECPATH is injected by PyInstaller as the directory containing this spec.
ROOT = os.path.abspath(os.path.join(SPECPATH, os.pardir))

# --- data files & tricky dependencies -------------------------------------
# The web UI is served read-only from inside the bundle. The JMdict source still
# downloads to the user's data dir on first run (see server/paths.py).
datas = [(os.path.join(ROOT, "web"), "web")]
binaries = []
hiddenimports = ["server.main"]

# Bundle the whisper STT model when it's present at build time (CI downloads it
# into models/ before this step). It lands at _internal/models inside the frozen
# app, where stt.py looks for it — so voice input works on a fresh install with
# no extra download. Optional: a local build without the file still succeeds.
_whisper_model = os.path.join(ROOT, "models", "ggml-small.bin")
if os.path.exists(_whisper_model):
    datas.append((_whisper_model, "models"))

# Packages that ship data files or use dynamic imports PyInstaller can miss.
for pkg in ("unidic_lite", "fugashi", "pykakasi", "jaconv"):
    try:
        d, b, h = collect_all(pkg)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception:
        pass

# uvicorn[standard] resolves its loop/protocol implementations at runtime.
hiddenimports += collect_submodules("uvicorn")
hiddenimports += [
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
    "anyio",
]

# --- icon (generated by CI before the build; optional locally) ------------
_icon = os.path.join(ROOT, "packaging", "kaiwa.icns" if IS_MAC else "kaiwa.ico")
ICON = _icon if os.path.exists(_icon) else None

a = Analysis(
    [os.path.join(ROOT, "launcher.py")],
    pathex=[ROOT],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Kaiwa",
    console=False,
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    name="Kaiwa",
)

if IS_MAC:
    app = BUNDLE(
        coll,
        name="Kaiwa.app",
        icon=ICON,
        bundle_identifier="com.kroogies.kaiwa",
        info_plist={
            "CFBundleName": "Kaiwa",
            "CFBundleDisplayName": "Kaiwa",
            "NSHighResolutionCapable": True,
            "LSUIElement": False,
        },
    )
